# Generated by Django 6.0.1 on 2026-01-21 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stok', models.IntegerField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alat', to='alat.kategori')),
            ],
        ),
    ]
