# Generated by Django 6.0.1 on 2026-01-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alat', '0002_alat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='nama',
            new_name='name',
        ),
    ]
