# Generated by Django 6.0.1 on 2026-01-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alat', '0003_rename_nama_kategori_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alat',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='kategori',
            old_name='name',
            new_name='nama',
        ),
    ]
